In [1]:
#1.Bayes Theorem for classification

# Prior probabilities
P_A = 0.6
P_B = 0.4

# Likelihoods
P_x_given_A = 0.7
P_x_given_B = 0.2

# Evidence
P_x = P_x_given_A * P_A + P_x_given_B * P_B

# Posterior
P_A_given_x = (P_x_given_A * P_A) / P_x
P_B_given_x = (P_x_given_B * P_B) / P_x

print("Posterior A:", P_A_given_x)
print("Posterior B:", P_B_given_x)


Posterior A: 0.84
Posterior B: 0.16000000000000003


In [7]:
#2. Maximum Likelihood Estimator 

import numpy as np

# Given dataset
data = np.array([12, 15, 14, 10, 18, 20, 16])

# Step 1: Compute Mean (MLE)
mean_mle = np.sum(data) / len(data)

# Step 2: Compute Variance (MLE)
variance_mle = np.sum((data - mean_mle) ** 2) / len(data)

print("Dataset:", data)
print("Estimated Mean (MLE):", mean_mle)
print("Estimated Variance (MLE):", variance_mle)


Dataset: [12 15 14 10 18 20 16]
Estimated Mean (MLE): 15.0
Estimated Variance (MLE): 10.0


In [9]:
#3. Naive Bayes Classifier

import math

# Training data
classes = ['Yes', 'No']
prior = {'Yes': 0.6, 'No': 0.4}

likelihood = {
    'Yes': [0.8, 0.7],
    'No': [0.3, 0.4]
}

# Test sample
x = [1, 1]

posterior = {}
for c in classes:
    prob = prior[c]
    for i in range(len(x)):
        prob *= likelihood[c][i]
    posterior[c] = prob

print(posterior)
print("Predicted Class:", max(posterior, key=posterior.get))


{'Yes': 0.33599999999999997, 'No': 0.048}
Predicted Class: Yes


In [ ]:
#4 Naive Bayes using Sckit-Learn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

X, y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 1.0


In [13]:
#5.Expectation–Maximization (EM) Algorithm

import numpy as np
from sklearn.mixture import GaussianMixture

# Dataset
X = np.array([[1], [2], [3], [4], [8], [9], [10], [11]])

# Create Gaussian Mixture Model
gmm = GaussianMixture(n_components=2, max_iter=100)

# Fit model
gmm.fit(X)

# Predict cluster labels
labels = gmm.predict(X)

print("Data Points:")
print(X.flatten())

print("\nCluster Means:")
print(gmm.means_)

print("\nCluster Labels:")
print(labels)


Data Points:
[ 1  2  3  4  8  9 10 11]

Cluster Means:
[[2.50001376]
 [9.49998624]]

Cluster Labels:
[0 0 0 0 1 1 1 1]
