In [ ]:
#1. KNN from Scratch

import math
from collections import Counter

def euclidean(p1, p2):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(p1, p2)))

def knn(train_X, train_y, test, k):
    distances = []
    for i in range(len(train_X)):
        dist = euclidean(train_X[i], test)
        distances.append((dist, train_y[i]))
    distances.sort(key=lambda x: x[0])
    neighbors = [label for _, label in distances[:k]]
    return Counter(neighbors).most_common(1)[0][0]

X = [[1,2], [2,3], [3,4], [6,7]]
y = ['A','A','B','B']

print("Predicted Class:", knn(X, y, [2,2], 3))


Predicted Class: A


In [ ]:
#2. KNN using Scikit-learn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.9666666666666667
Confusion Matrix:
 [[10  0  0]
 [ 0  7  1]
 [ 0  0 12]]


In [3]:
#3. Logically Weighted Regression

import numpy as np

# Dataset
X = np.array([1,2,3,4,5], dtype=float)
y = np.array([2,4,6,8,10], dtype=float)

# Add bias term
X = np.c_[np.ones(len(X)), X]

def lwr(x, X, y, tau):
    m = X.shape[0]
    W = np.eye(m)
    for i in range(m):
        diff = X[i] - x
        W[i,i] = np.exp(-(diff @ diff) / (2 * tau * tau))
    theta = np.linalg.pinv(X.T @ W @ X) @ X.T @ W @ y
    return x @ theta

# Prediction
tau = 0.5
for i in range(len(X)):
    print("Predicted:", round(lwr(X[i], X, y, tau), 2))


Predicted: 2.0
Predicted: 4.0
Predicted: 6.0
Predicted: 8.0
Predicted: 10.0


In [5]:
#4. Radial Basis Function (RBF) Network

import numpy as np

def rbf(x, c, sigma):
    return np.exp(-np.linalg.norm(x-c)**2 / (2*sigma**2))

X = np.array([[1],[2],[3]])
centers = np.array([[1],[3]])

features = [[rbf(x, c, 1) for c in centers] for x in X]
print("RBF Features:", features)



RBF Features: [[np.float64(1.0), np.float64(0.1353352832366127)], [np.float64(0.6065306597126334), np.float64(0.6065306597126334)], [np.float64(0.1353352832366127), np.float64(1.0)]]


In [6]:
#5. Case-Based Learning System

import math

cases = {
    (1,2): "Low",
    (4,5): "Medium",
    (7,8): "High"
}

def similarity(a, b):
    return math.sqrt(sum((x-y)**2 for x,y in zip(a,b)))

query = (5,6)
result = min(cases, key=lambda c: similarity(c, query))
print("Predicted Case:", cases[result])


Predicted Case: Medium
